name: tyrian
version: 0.0.1
description:
  A game using  play_phaser library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/tyrian
dependencies:
  browser: any
  play_phaser:
    path: ../play_phaser

transformers:
- $dart2js:
    checked: false
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true